micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8080
hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hello from Services!"
  config:
    greeting:
      de: "Hallo"
      en: "Hello"